Changes in Platform
WidhyaOrg/WidhyaOrg.github.io pull request #7
Opened 2019-06-24 04:18 UTC by babu1998

Adding 7 images ( for browse_missions )
Adding 1 css file ( for html file browse_missions )
Adding 1 html file ( browse_missions.html )

2019-06-24 05:10 UTC, babu1998 commented
browse page done
main page done
opportunity page done
microtask page done
new dashboard page done

2019-06-24 05:11 UTC, babu1998 commented
Uploaded all the web pages

2019-06-24 05:56 UTC, rahulkumaran commented
@babu1998 you don't need to add the style for body and font in every css file. It's already present in the layout.html file.
If you need to make any changes to font-style or bg color ever, just make changes in the layout.html file !
Remove the unnecesary css files.

2019-06-24 05:57 UTC, rahulkumaran requested changes
Make the changes mentioned in the previous comment and on whatsapp.

2019-06-26 05:50 UTC, babu1998 commented
deleted unnecessary css files

2019-06-27 08:19 UTC, rahulkumaran approved these changes

2019-06-27 08:19 UTC, rahulkumaran commented on static/css/browse_missions.css
> +* {
This file needs to be deleted

2019-06-27 08:19 UTC, rahulkumaran commented on static/css/dashboard.css
> +* {
this file needs to be deleted

2019-06-27 08:19 UTC, rahulkumaran commented on static/css/main.css
> +* {
What's this css file for? Is it for the gradient?
Also, please remove the part from lines 1-8

2019-06-27 08:19 UTC, rahulkumaran commented on templates/browse_missions.html
> +		<img src="../static/images/widhyalogo.jpg" style="height:50px;width:50px" class="navbar-brand my-auto">
Image source should be in Flask format

2019-06-27 08:19 UTC, rahulkumaran commented on templates/browse_missions.html
> +    <ul class="navbar-nav ">
Remove lines 19-30 because when you extend layout.html, Navbar will be included in that.

2019-06-27 08:19 UTC, rahulkumaran commented on templates/browse_missions.html
> +  <img src="../static/images/googlelogo.png" class="card-img-top" alt="..." style="height:250px !important;width:250px !important;">
Make src changes

2019-06-27 08:19 UTC, rahulkumaran commented on templates/browse_missions.html
> +  <img src="../static/images/applelogo.png" class="card-img-top" alt="..." style="height:250px !important;width:250px !important;">
Make src changes

2019-06-27 08:19 UTC, rahulkumaran commented on templates/browse_missions.html
> +  <img src="../static/images/facebooklogo.png" class="card-img-top" alt="..." style="height:250px !important;width:250px !important;">
Make src changes

2019-06-27 08:19 UTC, rahulkumaran commented on templates/browse_missions.html
> +  <img src="../static/images/amazonlogo.png" class="card-img-top" alt="..." style="height:250px !important;width:250px !important;">
Make src changes

2019-06-27 08:19 UTC, rahulkumaran commented on templates/browse_missions.html
> +  <img src="../static/images/microsoftlogo.jpg" class="card-img-top" alt="..." style="height:250px !important;width:250px !important;">
Make src changes

2019-06-27 08:19 UTC, rahulkumaran commented on templates/browse_missions.html
> +  <img src="../static/images/localelogo.png" class="card-img-top" alt="..." style="height:250px !important;width:250px !important;">
Make src changes

2019-06-27 08:19 UTC, rahulkumaran commented on templates/browse_missions.html
> +  <img src="../static/images/discordlogo.png" class="card-img-top" alt="..." style="height:250px !important;width:250px !important;">
Make src changes

2019-06-27 08:19 UTC, rahulkumaran commented on templates/browse_missions.html
> +<!DOCTYPE html>
Remove code from lines 1-13

2019-06-27 08:19 UTC, rahulkumaran commented on templates/layout.html
> +	 <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
please link the main.css stylesheet here!

2019-06-27 08:19 UTC, rahulkumaran commented on static/css/browse_missions.css
> +* {
This file is not required because we extend layout.html to all pages ! Delete this

2019-06-27 08:19 UTC, rahulkumaran commented on static/css/dashboard.css
> +* {
This also isn't required. Please delete it

2019-06-27 08:19 UTC, merged